-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0hmyKmkwG8H8ifrFXBx8wEvX9XtfxeR0Hgw0aVXGF1agCgYIKoZIzj0DAQehRANCAATipskI0LIVEoNPQYsZSeBKaecDMo9fsWKqGuaK4FuNY9BA/sJht36lSLdoTOuHITFxFns0cTm1b9eULycLX9Q+
-----END PRIVATE KEY-----