# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConfirmaConsultaIOS’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'JTAppleCalendar', '~> 7.0'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'


  # Pods for ConfirmaConsulta

  target 'ConfirmaConsultaIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConfirmaConsultaIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
